package com.example.shopping.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/*
 * create table shoppingrole(id bigint primary key generated by default as IDENTITY, name varchar(100) not null);
 * 
 * create table user_role(user_id bigint not null, role_id bigint not null,
 	constraint fk_user_id foreign key(user_id) references shoppinguser(id),
 	constraint fk_role_id foreign key(role_id) references shoppingrole(id));
 */
@Entity
@Table(name="shoppingrole")
public class Role {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	
	@Enumerated(EnumType.STRING)	
	@Column(name="name")
	private Roles roleName;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Roles getRoleName() {
		return roleName;
	}

	public void setRoleName(Roles roleName) {
		this.roleName = roleName;
	}
	
}
